export const recommenedListData = [
  {
    id: 1,
    name: 'Burger King',
    imageUrl: require('@assets/tabicons/burger.jpg'),
    time: '30-35 min',
    distance: '1.2 km',
    discount: '40% OFF',
    discountAmount: 'UPTO ₹80',
    rating: 4.2,
    cuisine: 'American, Fast Food',
    isBookmarked: false,
  },
  {
    id: 2,
    name: 'Paradise Paratha',
    imageUrl: require('@assets/tabicons/paratha.jpg'),
    time: '25-30 min',
    distance: '0.8 km',
    discount: '50% OFF',
    discountAmount: 'UPTO ₹100',
    rating: 4.5,
    cuisine: 'North Indian',
    isBookmarked: true,
  },
  {
    id: 3,
    name: 'Pizza Hut',
    imageUrl: require('@assets/tabicons/pizza.jpg'),
    time: '35-40 min',
    distance: '2.1 km',
    discount: '30% OFF',
    discountAmount: 'UPTO ₹120',
    rating: 4.0,
    cuisine: 'Italian, Fast Food',
    isBookmarked: false,
  },
  {
    id: 4,
    name: 'South Indian Delight',
    imageUrl: require('@assets/tabicons/rice_curry.jpg'),
    time: '20-25 min',
    distance: '1.5 km',
    discount: '25% OFF',
    discountAmount: 'UPTO ₹75',
    rating: 4.3,
    cuisine: 'South Indian',
    isBookmarked: false,
  },
  {
    id: 5,
    name: 'Fresh & Healthy',
    imageUrl: require('@assets/tabicons/salad.jpeg'),
    time: '15-20 min',
    distance: '0.5 km',
    discount: '20% OFF',
    discountAmount: 'UPTO ₹60',
    rating: 4.6,
    cuisine: 'Healthy Food, Salads',
    isBookmarked: true,
  },
  {
    id: 6,
    name: 'Samosa Corner',
    imageUrl: require('@assets/tabicons/samosa.jpg'),
    time: '15-20 min',
    distance: '0.3 km',
    discount: '35% OFF',
    discountAmount: 'UPTO ₹50',
    rating: 4.4,
    cuisine: 'Street Food, Snacks',
    isBookmarked: false,
  },
];
